pipeline {
    agent { label ' node1 || node2' }

    environment {
        IMAGE_NAME = "webhook-nginx:${BUILD_NUMBER}"
    }

    triggers {
        githubPush()
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/sudhir271009/jenkins-repo.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('webhook') {
                    sh '''
                      docker build -t $IMAGE_NAME .
                    '''
                }
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                  docker rm -f webhook-nginx || true
                  docker run -d --name webhook-nginx -p 8085:80 $IMAGE_NAME
                '''
            }
        }
    }
}
